#!/usr/bin/env python
import sys
import click
# Import specific command groups
from commands import todo, greetings


@click.group(help="Azzy's CLI tool")
def cli():
    """Main entry point for Azzy's CLI Tool."""
    print("\nPYTHON VERSION: ", sys.version, "\n")
    pass
    

# adds command groups to the cli group
# left side = command groups, right side = cli groups

# Add the `todo` command group
cli.add_command(todo.todo)
cli.add_command(greetings.greetings)

if __name__ == "__main__":
    cli()
