#!/usr/bin/env python
import sys
import click
# Import specific command groups
from commands import todo, greetings, joke, youtube


@click.group(help="Azzy's CLI tool")
def cli():
    """Main entry point for Azzy's CLI Tool."""
    pass
    

# adds command groups to the cli group
# left side = command groups, right side = cli groups

# Add the `todo` command group
cli.add_command(todo.todo, name="todo")
cli.add_command(greetings.greetings, name="greetings")
cli.add_command(joke.joke, name="joke")
cli.add_command(youtube.youtube, name="youtube")

if __name__ == "__main__":
    cli()
